import {
  Loader2,
  Mail,
  Github,
  Facebook,
  Twitter,
  Instagram,
  Linkedin,
  ChevronLeft,
  ChevronRight,
  Check,
  X,
  AlertCircle,
  AlertTriangle,
  Info,
  Search,
  Menu,
  Settings,
  User,
  LogOut,
  Bell,
  Calendar,
  Clock,
  MapPin,
  Users,
  Star,
  Filter,
  ArrowUpDown,
  Chrome,
} from "lucide-react"

export const Icons = {
  spinner: Loader2,
  mail: Mail,
  github: Github,
  facebook: Facebook,
  twitter: Twitter,
  instagram: Instagram,
  linkedin: Linkedin,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  check: Check,
  x: X,
  alertCircle: AlertCircle,
  alertTriangle: AlertTriangle,
  info: Info,
  search: Search,
  menu: Menu,
  settings: Settings,
  user: User,
  logout: LogOut,
  bell: Bell,
  calendar: Calendar,
  clock: Clock,
  mapPin: MapPin,
  users: Users,
  star: Star,
  filter: Filter,
  arrowUpDown: ArrowUpDown,
  google: Chrome,
} 